name: 🐛 Проблема со скриптом или стратегией
description: "Перед созданием issue убедитесь, что вы выполнили все шаги проверки."
title: "[ISSUE] "
labels: ["bug", "strategy"]
assignees: []

body:
  - type: markdown
    attributes:
      content: |
        Спасибо за использование **zapret-discord-youtube-linux**!  
        Перед созданием issue, пожалуйста, выполните все шаги ниже и заполните информацию.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Проверено перед созданием issue"
      options:
        - label: "Я прочитал README и документацию полностью"
          required: true
        - label: "Я проверил существующие issues и не нашёл ответа на свой вопрос"
          required: true
        - label: "Я проверил, что проблема воспроизводится на всех скриптах/стратегиях"
          required: true
        - label: "Я использую x86_64 или пробовал заменить бинарный файл `nfqws` от bol-van для моей архитектуры"
          required: true
        - label: "Я сделал `sudo bash main_script.sh -debug` и собрал логи"
          required: true
        - label: "Я полностью удалял директорию и устанавливал заново, строго следуя инструкциям из README"
          required: true
        - label: "Я пытался решить проблему самостоятельно через Google или ChatGPT, безрезультатно"
          required: true

  - type: input
    id: os_version
    attributes:
      label: "ОС и версия (например, Ubuntu 24.04 или Arch Linux)"
      placeholder: "Ubuntu 24.04"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Описание проблемы"
      description: "Опишите подробно, что именно не работает (скрипт падает, стратегия не применяет правила и т.д.)"
      placeholder: "Например, скрипт не создаёт правила nftables или стратегия general_alt5.bat не работает"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Логи / вывод команды `-debug` и сервисные логи (если применимо)"
      description: |
        Вставьте сюда:
        - вывод `sudo bash main_script.sh -debug`  
        - если проблема возникает при автозапуске через сервис: `journalctl -u zapret_discord_youtube.service`
      placeholder: "Paste debug logs and service logs here"
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: "Шаги воспроизведения"
      description: |
        Вставьте сюда подряд команды, которые выполняли, начиная с git clone:
      placeholder: "Paste your shell steps here"
    validations:
      required: true